version: '3'

services:
  app:
    build: ./Dockerfile.prod
    container_name: app
    # entrypoint: dockerize -template ./.docker/app/.env:.env  -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    # environment:
    #  - MYSQL_HOST=db
    #  - MYSQL_DATABASE=laravel
    #  - MYSQL_USERNAME=root
    #  - MYSQL_PASSWORD=root  
    volumes:
     - .:/var/www
    networks:
     - app-network
    depends_on:
     - db
     - redis

  nginx:
    build: .docker/nginx
    container_name: nginx
    # command: dockerize -template ./.docker/nginx/.env:.env
    # environment:
    #   - NGINX_PORT=80
    #   - APP_NAME=app
    #   - APP_PORT=9000
    restart: always
    tty: true
    ports:
     - "8000:80"
    volumes:
      - .:/var/www
    networks:
     - app-network
    depends_on:
     - app

  db:
    build: .docker/mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
     - "3306:3306"
    volumes:
     - ./.docker/dbdata:/var/lib/mysql
    environment:
     - MYSQL_DATABASE=laravel
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_USER=root
    networks:
     - app-network

  redis:
    image: redis:alpine
    expose:
     - 6379
    networks:
     - app-network

networks:
  app-network:
    driver: bridge
